use crate::{eval_string, init};
use test_case::test_case;

#[test_case("2+2", "4"; "sum")]
#[test_case("abs(4.0 * 10 + 2)", "42"; "abs")]
#[test_case("abs(-123)", "123"; "abs of negative")]
#[test_case("10/20", "1/2"; "division of integers")]
#[test_case("1/(2/3)", "3/2"; "reciprocal of integers")]
#[test_case("1/0.5", "2"; "reciprocal of float")]
#[test_case("(10/10)/0.5", "2"; "division by float")]
#[test_case("sqrt(9) = 9^(1/2)", "3"; "sqrt")]
#[test_case("4^(3/2)", "8"; "rational power")]
#[test_case("-4^(3/2)", "8"; "negative base to rational power")]
#[test_case("4.0^(3/2)", "8"; "float negative base to rational power")]
#[test_case("0^2", "0"; "zero to positive power")]
#[test_case("0^(-5)", "NaN"; "zero to negative power")]
#[test_case("0^(-0.5)", "NaN"; "zero to negative float power")]
#[test_case("(-4*4*4)^(-1/3)", "-0.25"; "negative number to negative rational power")]
#[test_case("-27^(1/3)", "-3"; "negative base to rational odd power")]
#[test_case("1+2i", "1+2i"; "complex number")]
#[test_case("2+4*10", "42"; "order of operations")]
#[test_case("10 % 3", "1"; "modulo operation")]
#[test_case("25 % 5", "0"; "modulo zero result")]
#[test_case("(-8) % 3", "-2"; "modulo negative")]
#[test_case("2^10", "1024"; "power of 2")]
#[test_case("(-2)^3", "-8"; "negative to odd power")]
#[test_case("(-2)^2", "4"; "negative to even power")]
#[test_case("(1/2)+(1/3)", "5/6"; "sum of rationals")]
#[test_case("(2/3)*(3/4)", "1/2"; "product of rationals")]
#[test_case("(1/2)-(1/4)", "1/4"; "difference of rationals")]
#[test_case("(3/4)^2", "9/16"; "rational squared")]
#[test_case("(1+2i)+(3+4i)", "4+6i"; "sum of complex")]
#[test_case("(2+3i)*(4+5i)", "-7+22i"; "product of complex")]
#[test_case("(5+0i)-(3+0i)", "2+0i"; "difference of complex")]
#[test_case("abs(3+4i)", "5"; "absolute of complex")]
#[test_case("(1+i)^2", "0+2i"; "complex squared")]
#[test_case("x=10;y=x/5;2*y", "4"; "using variables")]
#[test_case("a=5;b=10;a+b", "15"; "multiple variables")]
#[test_case("0.5^-1", "2"; "float to negative power")]
#[test_case("1<2<3", "3"; "inequality 1")]
#[test_case("10<20>15", "15"; "inequality 2")]
#[test_case("[] = []", "[]"; "empty vectors are equal")]
#[test_case("[1,2,3] = [1,2,3]", "[1, 2, 3]"; "equal vectors")]
#[test_case("[1,2,3] != [1,2,3,1]", "[1, 2, 3, 1]"; "non-equal vectors")]
#[test_case("x=[1,2,3]; x < x+1", "[2, 3, 4]"; "vector is less than vector")]
#[test_case("0 < [1,2,3]", "[1, 2, 3]"; "constant is less than vector")]
#[test_case("[1,2,3] >= 1", "1"; "vector is greater or equal than constant")]
#[test_case("2 < 4~7", "4~7"; "compare number to interval")]
#[test_case("4~7 < 10", "10"; "compare interval to number")]
#[test_case("5 != 6", "6"; "not equal succeeds")]
#[test_case("10 >= 10", "10"; "greater equal boundary")]
#[test_case("10 <= 10", "10"; "less equal boundary")]
#[test_case("1=1=1=1", "1"; "equality")]
#[test_case("floor(12.345)", "12"; "floor of float")]
#[test_case("floor(12.345 + 0i)", "12"; "floor of complex")]
#[test_case("ceil(12.345)", "13"; "ceil of float")]
#[test_case("floor(10/3)", "3"; "floor of rational")]
#[test_case("ceil(10/3)", "4"; "ceil of rational")]
#[test_case("ln(e)", "1"; "ln of e")]
#[test_case("exp(1) = e", "2.718281828459045"; "exp of 1")]
#[test_case("rat(pi) = pi", "3.141592653589793"; "rat of pi")]
#[test_case("i^2 = -1", "-1"; "complex i squared")]
#[test_case("5^-3", "1/125"; "integer to negative power")]
#[test_case("sqrt(i^2) = i", "0+1i"; "sqrt of complex")]
#[test_case("log(exp(42))", "42"; "log of exp")]
#[test_case("sin(asin(0.45))", "0.45"; "sin of asin")]
#[test_case("sqrt(42^2)", "42"; "sqrt of square")]
#[test_case("cbrt(42^3)", "42"; "cbrt of third power")]
#[test_case("log10(1000)", "3"; "log10 of thousand")]
#[test_case("log2(8)", "3"; "log2 of 8")]
#[test_case("e^0", "1"; "e to zero")]
#[test_case("0^0", "1"; "zero to zero")]
#[test_case("log2(2^17)", "17"; "log2 of power of 2")]
#[test_case("1/0 or 2", "2"; "lhs or")]
#[test_case("1 or 2/0", "1"; "rhs or")]
#[test_case("1/0 and 2", "NaN"; "lhs and")]
#[test_case("1 and 2/0", "NaN"; "rhs and")]
#[test_case("min([])", "NaN"; "min with no arguments")]
#[test_case("min([2,3,1])", "1"; "min of integers")]
#[test_case("max([])", "NaN"; "max with no arguments")]
#[test_case("max([2,3,1])", "3"; "max of integers")]
#[test_case("min([5])", "5"; "min with single argument")]
#[test_case("max([5])", "5"; "max with single argument")]
#[test_case("min([-5,-10,-1])", "-10"; "min negative numbers")]
#[test_case("max([-5,-10,-1])", "-1"; "max negative numbers")]
#[test_case("min([1/2,1/3,1/4])", "1/4"; "min of rationals")]
#[test_case("choose(0,10)", "NaN"; "choose 10 of 0")]
#[test_case("choose(0,0)", "1"; "choose 0 of 0")]
#[test_case("choose(1,1)", "1"; "choose 1 of 1")]
#[test_case("choose(4,2)", "6"; "choose 2 of 4")]
#[test_case("choose(5,2)", "10"; "choose 2 of 5")]
#[test_case("choose(10,5)", "252"; "choose 5 of 10")]
#[test_case("choose(6,3)", "20"; "choose 3 of 6")]
#[test_case("0!", "1"; "zero factorial")]
#[test_case("1!", "1"; "one factorial")]
#[test_case("10!", "3628800"; "ten factorial")]
#[test_case("(3+5*2)!", "6227020800"; "factorial")]
#[test_case("6!", "720"; "six factorial")]
#[test_case("if 100 then 1 else 2", "1"; "lhs if 1")]
#[test_case("if nan then 1 else 2", "2"; "rhs if 1")]
#[test_case("if 1=1 then 1 else 2", "1"; "lhs if 2")]
#[test_case("if 1=2 then 1 else 2", "2"; "rhs if 2")]
#[test_case("if 1=1 then if 2=2 then 1 else 2 else if 3=3 then 4 else 5", "1"; "lhs lhs if")]
#[test_case("if 1=0 then if 2=2 then 1 else 2 else if 3=3 then 4 else 5", "4"; "rhs lhs if")]
#[test_case("if 1<2 then 10 else 20", "10"; "condition with comparison")]
#[test_case("if 2<1 then 10 else 20", "20"; "failed condition")]
#[test_case("rat(0.5)", "1/2"; "rat of fraction")]
#[test_case("rat(0.25)", "1/4"; "rat of quarter")]
#[test_case("rat(0.125)", "1/8"; "rat of eighth")]
#[test_case("float(rat(pi)) = pi", "3.141592653589793"; "float after rat")]
#[test_case("int(17.0)", "17"; "int from float")]
#[test_case("int(5+0i)", "5"; "int from complex")]
#[test_case("int(6/2)", "3"; "int from rational")]
#[test_case("load(examples/fibonacci.rc)", "4181"; "load fibonacci")]
#[test_case("fun f(x) x; f(84/2)", "42"; "identity fun call")]
#[test_case("x=1; fun f(x) x; f(2); x", "1"; "variable scope 1")]
#[test_case("x=1; fun f(x) x; f(2)", "2"; "variable scope 2")]
#[test_case("fun double(x) 2*x; double(21)", "42"; "simple function")]
#[test_case("fun add(a,b) a+b; add(10,32)", "42"; "two argument function")]
#[test_case("fun sq(x) x*x; sq(7)", "49"; "square function")]
#[test_case("fun f(x) x+1; fun g(x) f(x)*2; g(5)", "12"; "nested function calls")]
#[test_case("fun f(x) { y=x*10; x+y }; f(1)", "11"; "function with multiple instructions")]
#[test_case("fun f() { 20*2+2 }; f()", "42"; "function with no arguments")]
#[test_case("sqrt(-1)", "NaN"; "sqrt of negative")]
#[test_case("1/(1-1)", "NaN"; "division by zero")]
#[test_case("(-5)!", "NaN"; "negative factorial")]
#[test_case("0.5!", "NaN"; "non-integer factorial")]
#[test_case("choose(10,-1)", "NaN"; "choose with negative k")]
#[test_case("choose(3,5)", "NaN"; "choose k greater than n")]
#[test_case("5!=120", "120"; "not equal")]
#[test_case("(5!)=120", "120"; "factorial with equal")]
#[test_case("0 <= rand() < 1", "1"; "rand is within bounds")]
#[test_case("len(rand(13))", "13"; "rand with count")]
#[test_case("1 = 1~1 = 1/1 = 1.0", "1"; "equivalence of numbers types")]
#[test_case("len([])", "0"; "len of empty vector")]
#[test_case("len([1,2,3,4])", "4"; "len of non-empty vector")]
#[test_case("rev([])", "[]"; "rev of empty vector")]
#[test_case("rev([1,2,3,4])", "[4, 3, 2, 1]"; "rev of non-empty vector")]
#[test_case("sum([])", "0"; "sum of empty vector")]
#[test_case("sum([1,2,3,4])", "10"; "sum of non-empty vector")]
#[test_case("prod([])", "1"; "prod of empty vector")]
#[test_case("prod([1,2,3,4])", "24"; "prod of non-empty vector")]
#[test_case("seq(1,5)", "[1, 2, 3, 4, 5]"; "range")]
#[test_case("seq(1,10,3)", "[1, 4, 7, 10]"; "range with step")]
#[test_case("seq(0.1,1,0.3)", "[0.1, 0.4, 0.7, 1]"; "range for float")]
#[test_case("5 in 1~10", "5"; "in interval")]
#[test_case("2 in [1,2,3,4]", "2"; "in vector")]
#[test_case("[]:1", "NaN"; "extract from empty vector")]
#[test_case("[]:1~10", "[]"; "extract range from empty vector")]
#[test_case("[10,20,30,40,50]:2", "20"; "extact value from vector")]
#[test_case("[10,20,30,40,50]:21", "NaN"; "extract value our of range from vector")]
#[test_case("[10,20,30,40,50]:2~4", "[20, 30, 40]"; "extract slice from vector")]
#[test_case("[10,20,30,40,50]:1+2/2", "20"; "extract where index is expression")]
#[test_case("[10,20,30,40,50]:[2,1,100,3]", "[20, 10, NaN, 30]"; "extact using vector indexing")]
#[test_case("push([], [])", "[[]]"; "push value to empty vector")]
#[test_case("v=[]; push(v, -1); v", "[]"; "pushing does not mutate vector")]
#[test_case("push([1,2], 3, 4)", "[1, 2, 3, 4]"; "push values to vector")]
#[test_case("min(11~22)", "11"; "extract lower bound from interval")]
#[test_case("max(11~22)", "22"; "extract upper bound from interval")]
#[test_case("-5~3 | 0~7", "-5~7"; "interval hull")]
#[test_case("-5~3 & 0~7", "0~3"; "interval intersection")]
#[test_case("10 + [1,2,3]", "[11, 12, 13]"; "add const to vector")]
#[test_case("[1,2,3] + 100", "[101, 102, 103]"; "add vector to const")]
#[test_case("[1,2,3] + [10,20,30]", "[11, 22, 33]"; "add vectors")]
#[test_case("[10,20,30,40,50] + [1,2,3]", "[11, 22, 33, 41, 52]"; "cycle through vectors when adding them")]
#[test_case("[1, -1] * [10,20,30,40,50]", "[10, -20, 30, -40, 50]"; "cycle through vectors when multiplying them")]
#[test_case("-[1,2,3]", "[-1, -2, -3]"; "negate a vector")]
#[test_case("1 ?= 1", "1"; "integers have same types")]
#[test_case("1/4 ?= 55/19", "55/19"; "rationals have same types")]
#[test_case("[[[]],[]] ?= []", "[]"; "vectors have same types")]
#[test_case("1~5||-10~|-21||+|-100|", "101~121"; "absolute value parses correctly")]
#[test_case("-|5| != |-5|", "5"; "absolute value operation order")]
fn basic(input: &str, expexted: &str) {
    let (memory, funs) = init();
    let result = eval_string(input, memory, funs).expect("unexpected error");
    assert_eq!(result.to_string(), expexted)
}

#[test_case("1=2"; "equality")]
#[test_case("1!=1"; "not equal fails")]
#[test_case("5<5"; "less than fails")]
#[test_case("10>20"; "more than fails")]
#[test_case("100>20<3"; "inequality")]
#[test_case("1=1 and 1=2"; "rhs for and fails")]
#[test_case("1=2 and 1=1"; "lhs for and fails")]
#[test_case("1=2 or 1>2"; "rhs for or fails")]
#[test_case("sqrt(1,2,3,4,5)"; "too many arguments for primitive")]
#[test_case("fun f(x) x; f(1,2,3,4)"; "too many arguments for fun")]
#[test_case("if 1=1 then 42"; "if without else")]
#[test_case("load(wrong/file/name)"; "load non-existent file")]
#[test_case("x"; "uninitialized variable")]
#[test_case("x=1;x=2"; "unification failed")]
#[test_case("global=1; fun f(local) global; f(2)"; "global variable from function")]
#[test_case("fun f(x,y) x; f(1)"; "too few arguments")]
#[test_case("min"; "function call without parentheses")]
#[test_case("fun f(x) y; f(1)"; "undefined variable in function")]
#[test_case("rand(1,2,3)"; "rand with arguments")]
#[test_case("choose(1)"; "choose with one argument")]
#[test_case("choose(1,2,3)"; "choose with three arguments")]
#[test_case("fun f(x) x; f"; "function without call")]
#[test_case("unknownfunc(42)"; "unknown function call")]
#[test_case("-2 in 1~5"; "negative in interval assertion")]
#[test_case("20 in [1,5,10]"; "negative in vector assertion")]
#[test_case("2:1"; "extract from invalid lhs")]
#[test_case("[]:0"; "zero index")]
#[test_case("[1,2,3]:-5"; "negative index")]
#[test_case("1 ?= 11~22"; "integer and interval have different types")]
#[test_case("[] ?= 11~22"; "list and interval have different types")]
#[test_case("1 ?= 5.0"; "integer and float have different types")]
#[test_case("1/2 ?= 0.5"; "rational and float have different types")]
fn expect_error(input: &str) {
    let (memory, funs) = init();
    assert!(eval_string(input, memory, funs).is_err())
}

#[test_case("2 + 3", "5"; "int add")]
#[test_case("2.0 + 3.0", "5"; "float add")]
#[test_case("2/1 + 3/1", "5"; "rational add")]
#[test_case("(2+0i) + (3+0i)", "5+0i"; "complex add")]
#[test_case("2 + 3.0", "5"; "int float add")]
#[test_case("2/1 + 3", "5"; "rational int add")]
#[test_case("2.0 + 3/1", "5"; "float rational add")]
#[test_case("10 - 3", "7"; "int sub")]
#[test_case("10.0 - 3.0", "7"; "float sub")]
#[test_case("10/1 - 3/1", "7"; "rational sub")]
#[test_case("10 - 3.0", "7"; "int float sub")]
#[test_case("10/1 - 3", "7"; "rational int sub")]
#[test_case("4 * 5", "20"; "int mul")]
#[test_case("4.0 * 5.0", "20"; "float mul")]
#[test_case("4/1 * 5/1", "20"; "rational mul")]
#[test_case("4 * 5.0", "20"; "int float mul")]
#[test_case("4/1 * 5", "20"; "rational int mul")]
#[test_case("20 / 4", "5"; "int div")]
#[test_case("20.0 / 4.0", "5"; "float div")]
#[test_case("20/1 / 4/1", "5"; "rational div")]
#[test_case("20 / 4.0", "5"; "int float div")]
#[test_case("20/1 / 4", "5"; "rational int div")]
#[test_case("0 + 5", "5"; "zero add right")]
#[test_case("5 + 0", "5"; "zero add left")]
#[test_case("0 - 5", "-5"; "zero sub from")]
#[test_case("5 - 0", "5"; "zero sub right")]
#[test_case("0 * 5", "0"; "zero mul right")]
#[test_case("5 * 0", "0"; "zero mul left")]
#[test_case("0 / 5", "0"; "zero div left")]
#[test_case("0^5", "0"; "zero to positive power")]
#[test_case("0^0", "1"; "zero to zero power")]
#[test_case("5^0", "1"; "nonzero to zero power")]
#[test_case("(-5)^0", "1"; "negative to zero power")]
#[test_case("(1/2)^0", "1"; "rational to zero power")]
#[test_case("0.5^0", "1"; "float to zero power")]
#[test_case("1 * 42", "42"; "one mul right")]
#[test_case("42 * 1", "42"; "one mul left")]
#[test_case("42 / 1", "42"; "div by one")]
#[test_case("42^1", "42"; "power of one")]
#[test_case("1^42", "1"; "one to power")]
#[test_case("1^0", "1"; "one to zero")]
#[test_case("-5 + 3", "-2"; "negative add positive")]
#[test_case("5 + (-3)", "2"; "positive add negative")]
#[test_case("-5 + (-3)", "-8"; "negative add negative")]
#[test_case("-5 - 3", "-8"; "negative sub positive")]
#[test_case("5 - (-3)", "8"; "positive sub negative")]
#[test_case("-5 - (-3)", "-2"; "negative sub negative")]
#[test_case("-5 * 3", "-15"; "negative mul positive")]
#[test_case("5 * (-3)", "-15"; "positive mul negative")]
#[test_case("-5 * (-3)", "15"; "negative mul negative")]
#[test_case("-20 / 4", "-5"; "negative div positive")]
#[test_case("20 / (-4)", "-5"; "positive div negative")]
#[test_case("-20 / (-4)", "5"; "negative div negative")]
#[test_case("2^2", "4"; "positive to even power")]
#[test_case("2^3", "8"; "positive to odd power")]
#[test_case("(-2)^2", "4"; "negative to even power")]
#[test_case("(-2)^3", "-8"; "negative to odd power")]
#[test_case("(-2)^4", "16"; "negative to even power 4")]
#[test_case("(-2)^5", "-32"; "negative to odd power 5")]
#[test_case("(-3)^2", "9"; "negative three squared")]
#[test_case("(-3)^3", "-27"; "negative three cubed")]
#[test_case("3^-2", "1/9"; "positive to negative even power")]
#[test_case("3^-3", "1/27"; "positive to negative odd power")]
#[test_case("(-3)^-2", "1/9"; "negative to negative even power")]
#[test_case("4^(1/2)", "2"; "square root via power")]
#[test_case("8^(1/3)", "2"; "cube root via power")]
#[test_case("27^(1/3)", "3"; "27 cube root")]
#[test_case("16^(1/4)", "2"; "fourth root")]
#[test_case("32^(1/5)", "2"; "fifth root")]
#[test_case("9^(3/2)", "27"; "9 to 3/2 power")]
#[test_case("16^(3/4)", "8"; "16 to 3/4 power")]
#[test_case("(-8)^(1/3)", "-2"; "negative cube root")]
#[test_case("(-27)^(1/3)", "-3"; "negative 27 cube root")]
#[test_case("(1/4)^(1/2)", "0.5"; "rational square root")]
#[test_case("a=5; a^2 - a^2", "0"; "x squared minus x squared")]
#[test_case("a=3; (a+1)^2 - (a^2 + 2*a + 1)", "0"; "binomial expansion")]
#[test_case("a=4; a^3 - a*a*a", "0"; "cube identity")]
#[test_case("a=7; (a+2)*(a-2) - (a^2-4)", "0"; "difference of squares")]
#[test_case("a=2; b=3; (a+b)^2 - (a^2 + 2*a*b + b^2)", "0"; "square of sum")]
#[test_case("a=5; b=3; (a-b)^2 - (a^2 - 2*a*b + b^2)", "0"; "square of difference")]
#[test_case("a=2; a * (1/a)", "1"; "multiplicative inverse")]
#[test_case("a=7; a + (-a)", "0"; "additive inverse")]
#[test_case("a=3; b=5; c=7; a*(b+c) - (a*b + a*c)", "0"; "distributive property")]
#[test_case("x=0.5; sin(x)^2 + cos(x)^2", "1"; "pythagorean identity")]
#[test_case("sin(0)", "0"; "sin of zero")]
#[test_case("cos(0)", "1"; "cos of zero")]
#[test_case("tan(0)", "0"; "tan of zero")]
#[test_case("sin(pi/2)", "1"; "sin of pi/2")]
#[test_case("cos(pi)", "-1"; "cos of pi")]
#[test_case("ln(1)", "0"; "ln of one")]
#[test_case("ln(e)", "1"; "ln of e")]
#[test_case("ln(e^2)", "2"; "ln of e squared")]
#[test_case("ln(e^5)", "5"; "ln of e to 5")]
#[test_case("exp(0)", "1"; "exp of zero")]
#[test_case("log10(1)", "0"; "log10 of one")]
#[test_case("log10(10)", "1"; "log10 of ten")]
#[test_case("log10(100)", "2"; "log10 of hundred")]
#[test_case("log10(1000000)", "6"; "log10 of million")]
#[test_case("log2(1)", "0"; "log2 of one")]
#[test_case("log2(2)", "1"; "log2 of two")]
#[test_case("log2(4)", "2"; "log2 of four")]
#[test_case("log2(1024)", "10"; "log2 of 1024")]
#[test_case("log2(2^7)", "7"; "log2 power identity")]
#[test_case("x=3; y=5; ln(x*y) - (ln(x) + ln(y))", "0"; "log of product")]
#[test_case("sqrt(0)", "0"; "sqrt of zero")]
#[test_case("sqrt(1)", "1"; "sqrt of one")]
#[test_case("sqrt(4)", "2"; "sqrt of four")]
#[test_case("sqrt(9)", "3"; "sqrt of nine")]
#[test_case("sqrt(16)", "4"; "sqrt of sixteen")]
#[test_case("sqrt(25)", "5"; "sqrt of twenty five")]
#[test_case("sqrt(100)", "10"; "sqrt of hundred")]
#[test_case("x=16; sqrt(x) * sqrt(x) - x", "0"; "sqrt squared")]
#[test_case("x=5; y=4; sqrt(x*y) - sqrt(x)*sqrt(y)", "0"; "sqrt of product")]
#[test_case("sqrt(0.25)", "0.5"; "sqrt of quarter")]
#[test_case("sqrt(1/4)", "0.5"; "sqrt of one quarter rational")]
#[test_case("cbrt(0)", "0"; "cbrt of zero")]
#[test_case("cbrt(1)", "1"; "cbrt of one")]
#[test_case("cbrt(8)", "2"; "cbrt of eight")]
#[test_case("cbrt(27)", "3"; "cbrt of twenty seven")]
#[test_case("cbrt(64)", "4"; "cbrt of sixty four")]
#[test_case("cbrt(125)", "5"; "cbrt of one twenty five")]
#[test_case("cbrt(-1)", "-1"; "cbrt of negative one")]
#[test_case("cbrt(-8)", "-2"; "cbrt of negative eight")]
#[test_case("cbrt(-27)", "-3"; "cbrt of negative twenty seven")]
#[test_case("cbrt(7^3)", "7"; "cbrt of cube")]
#[test_case("abs(0)", "0"; "abs of zero")]
#[test_case("abs(5)", "5"; "abs of positive")]
#[test_case("abs(-5)", "5"; "abs of negative")]
#[test_case("abs(0.0)", "0"; "abs of zero float")]
#[test_case("abs(-42.5)", "42.5"; "abs of negative float")]
#[test_case("abs(5/7)", "5/7"; "abs of positive rational")]
#[test_case("abs(-5/7)", "5/7"; "abs of negative rational")]
#[test_case("floor(0)", "0"; "floor of zero")]
#[test_case("floor(5)", "5"; "floor of positive int")]
#[test_case("floor(-5)", "-5"; "floor of negative int")]
#[test_case("floor(5.1)", "5"; "floor of positive float")]
#[test_case("floor(5.9)", "5"; "floor of positive float near int")]
#[test_case("floor(-5.1)", "-6"; "floor of negative float")]
#[test_case("floor(-5.9)", "-6"; "floor of negative float near int")]
#[test_case("floor(7/2)", "3"; "floor of rational")]
#[test_case("floor(-7/2)", "-4"; "floor of negative rational")]
#[test_case("ceil(0)", "0"; "ceil of zero")]
#[test_case("ceil(5)", "5"; "ceil of positive int")]
#[test_case("ceil(-5)", "-5"; "ceil of negative int")]
#[test_case("ceil(5.1)", "6"; "ceil of positive float")]
#[test_case("ceil(5.9)", "6"; "ceil of positive float near int")]
#[test_case("ceil(-5.1)", "-5"; "ceil of negative float")]
#[test_case("ceil(-5.9)", "-5"; "ceil of negative float near int")]
#[test_case("ceil(7/2)", "4"; "ceil of rational")]
#[test_case("ceil(-7/2)", "-3"; "ceil of negative rational")]
#[test_case("0 % 5", "0"; "zero mod positive")]
#[test_case("5 % 5", "0"; "equal mod")]
#[test_case("7 % 3", "1"; "7 mod 3")]
#[test_case("10 % 4", "2"; "10 mod 4")]
#[test_case("17 % 5", "2"; "17 mod 5")]
#[test_case("100 % 7", "2"; "100 mod 7")]
#[test_case("(-10) % 3", "-1"; "negative mod positive")]
#[test_case("(-17) % 5", "-2"; "negative 17 mod 5")]
#[test_case("1 % 10", "1"; "small mod large")]
#[test_case("0!", "1"; "factorial of zero")]
#[test_case("1!", "1"; "factorial of one")]
#[test_case("2!", "2"; "factorial of two")]
#[test_case("3!", "6"; "factorial of three")]
#[test_case("4!", "24"; "factorial of four")]
#[test_case("5!", "120"; "factorial of five")]
#[test_case("7!", "5040"; "factorial of seven")]
#[test_case("(0.0)!", "1"; "factorial of zero float")]
#[test_case("(5.0)!", "120"; "factorial of five float")]
#[test_case("(0/1)!", "1"; "factorial of zero rational")]
#[test_case("(4/1)!", "24"; "factorial of four rational")]
#[test_case("(0+0i) + (0+0i)", "0+0i"; "complex zero add")]
#[test_case("(1+0i) * (2+0i)", "2+0i"; "real complex mul")]
#[test_case("(0+1i) * (0+1i)", "-1+0i"; "i squared")]
#[test_case("(2+3i) - (2+3i)", "0+0i"; "complex self subtract")]
#[test_case("(5+0i) / (5+0i)", "1+0i"; "complex self divide")]
#[test_case("abs(5+0i)", "5"; "abs of real complex")]
#[test_case("abs(0+5i)", "5"; "abs of imaginary")]
#[test_case("2 + 3 * 4", "14"; "add mul precedence")]
#[test_case("2 * 3 + 4", "10"; "mul add precedence")]
#[test_case("10 - 2 * 3", "4"; "sub mul precedence")]
#[test_case("2^3 * 2", "16"; "power mul precedence")]
#[test_case("2 * 2^3", "16"; "mul power precedence")]
#[test_case("2^2^3", "256"; "power right associative")]
#[test_case("(2+3) * 4", "20"; "parentheses override")]
#[test_case("2 * (3+4)", "14"; "parentheses override 2")]
#[test_case("2^20", "1048576"; "2 to 20th")]
#[test_case("2^30", "1073741824"; "2 to 30th")]
#[test_case("10^10", "10000000000"; "10 to 10th")]
#[test_case("999^2", "998001"; "999 squared")]
#[test_case("12!", "479001600"; "12 factorial")]
#[test_case("(1/2) + (1/2)", "1"; "half plus half")]
#[test_case("(1/3) + (1/3) + (1/3)", "1"; "thirds sum to one")]
#[test_case("(2/3) - (1/3)", "1/3"; "two thirds minus one third")]
#[test_case("(1/2) * (1/2)", "1/4"; "half times half")]
#[test_case("(2/3) * (3/4)", "1/2"; "two thirds times three fourths")]
#[test_case("(1/2) / (1/4)", "2"; "half div quarter")]
#[test_case("(3/4) / (1/2)", "3/2"; "three fourths div half")]
#[test_case("(2/3)^3", "8/27"; "rational cubed")]
#[test_case("(1/2)^-1", "2"; "rational to negative one")]
#[test_case("(2/3)^-1", "3/2"; "two thirds to negative one")]
fn numbers(input: &str, expexted: &str) {
    let (memory, funs) = init();
    let result = eval_string(input, memory, funs).expect("unexpected error");
    assert_eq!(result.to_string(), expexted)
}

#[test_case("[1,2,3] + [4,5,6]", "[5, 7, 9]"; "vector add")]
#[test_case("[10,20,30] - [1,2,3]", "[9, 18, 27]"; "vector sub")]
#[test_case("[2,3,4] * [5,6,7]", "[10, 18, 28]"; "vector mul")]
#[test_case("[20,30,40] / [2,3,4]", "[10, 10, 10]"; "vector div")]
#[test_case("[10,11,12] % [3,4,5]", "[1, 3, 2]"; "vector mod")]
#[test_case("[2,3,4]^[2,2,2]", "[4, 9, 16]"; "vector pow")]
#[test_case("[1,2,3] + 10", "[11, 12, 13]"; "vector add scalar")]
#[test_case("10 + [1,2,3]", "[11, 12, 13]"; "scalar add vector")]
#[test_case("[10,20,30] - 5", "[5, 15, 25]"; "vector sub scalar")]
#[test_case("100 - [10,20,30]", "[90, 80, 70]"; "scalar sub vector")]
#[test_case("[2,3,4] * 10", "[20, 30, 40]"; "vector mul scalar")]
#[test_case("10 * [2,3,4]", "[20, 30, 40]"; "scalar mul vector")]
#[test_case("[20,30,40] / 10", "[2, 3, 4]"; "vector div scalar")]
#[test_case("100 / [2,4,5]", "[50, 25, 20]"; "scalar div vector")]
#[test_case("[10,11,12] % 3", "[1, 2, 0]"; "vector mod scalar")]
#[test_case("[2,3,4]^2", "[4, 9, 16]"; "vector pow scalar")]
#[test_case("2^[1,2,3]", "[2, 4, 8]"; "scalar pow vector")]
#[test_case("-[1,2,3]", "[-1, -2, -3]"; "negate vector")]
#[test_case("-[-1,-2,-3]", "[1, 2, 3]"; "negate negative vector")]
#[test_case("-[0,1,-1]", "[0, -1, 1]"; "negate mixed vector")]
#[test_case("[0,0,0] + [1,2,3]", "[1, 2, 3]"; "zero vector add")]
#[test_case("[1,2,3] + [0,0,0]", "[1, 2, 3]"; "add zero vector")]
#[test_case("[1,2,3] - [0,0,0]", "[1, 2, 3]"; "sub zero vector")]
#[test_case("[0,0,0] * [1,2,3]", "[0, 0, 0]"; "zero vector mul")]
#[test_case("[1,2,3] * [0,0,0]", "[0, 0, 0]"; "mul zero vector")]
#[test_case("[0,0,0] / [1,2,3]", "[0, 0, 0]"; "zero vector div")]
#[test_case("[1,2,3]^[0,0,0]", "[1, 1, 1]"; "vector pow zero")]
#[test_case("[1,2,3] * [1,1,1]", "[1, 2, 3]"; "vector mul one")]
#[test_case("[1,1,1] * [4,5,6]", "[4, 5, 6]"; "one vector mul")]
#[test_case("[4,5,6] / [1,1,1]", "[4, 5, 6]"; "vector div one")]
#[test_case("[1,2,3]^[1,1,1]", "[1, 2, 3]"; "vector pow one")]
#[test_case("[1,2,3,4,5,6] + [10,20]", "[11, 22, 13, 24, 15, 26]"; "long vector add short cycles")]
#[test_case("[10,20] + [1,2,3,4,5,6]", "[11, 22, 13, 24, 15, 26]"; "short vector add long cycles")]
#[test_case("[1,2,3,4] * [10,100]", "[10, 200, 30, 400]"; "vector mul with cycling")]
#[test_case("[] + []", "[]"; "empty add empty")]
#[test_case("[] - []", "[]"; "empty sub empty")]
#[test_case("[] * []", "[]"; "empty mul empty")]
#[test_case("len([])", "0"; "len empty")]
#[test_case("len([1])", "1"; "len singleton")]
#[test_case("len([1,2,3,4,5])", "5"; "len five elements")]
#[test_case("sum([])", "0"; "sum empty")]
#[test_case("sum([1])", "1"; "sum singleton")]
#[test_case("sum([1,2,3,4,5])", "15"; "sum five elements")]
#[test_case("sum([1,-1,2,-2])", "0"; "sum to zero")]
#[test_case("prod([])", "1"; "prod empty")]
#[test_case("prod([5])", "5"; "prod singleton")]
#[test_case("prod([1,2,3,4])", "24"; "prod four elements")]
#[test_case("prod([1,2,0,4])", "0"; "prod with zero")]
#[test_case("min([])", "NaN"; "min empty")]
#[test_case("min([42])", "42"; "min singleton")]
#[test_case("min([3,1,4,1,5])", "1"; "min multiple")]
#[test_case("min([-5,0,5])", "-5"; "min with negative")]
#[test_case("max([])", "NaN"; "max empty")]
#[test_case("max([42])", "42"; "max singleton")]
#[test_case("max([3,1,4,1,5])", "5"; "max multiple")]
#[test_case("max([-5,0,5])", "5"; "max with negative")]
#[test_case("rev([])", "[]"; "rev empty")]
#[test_case("rev([1])", "[1]"; "rev singleton")]
#[test_case("rev([1,2,3])", "[3, 2, 1]"; "rev three elements")]
#[test_case("[10,20,30]:1", "10"; "index first")]
#[test_case("[10,20,30]:2", "20"; "index middle")]
#[test_case("[10,20,30]:3", "30"; "index last")]
#[test_case("[10,20,30,40,50]:1~3", "[10, 20, 30]"; "slice start")]
#[test_case("[10,20,30,40,50]:3~5", "[30, 40, 50]"; "slice end")]
#[test_case("[10,20,30,40,50]:2~4", "[20, 30, 40]"; "slice middle")]
#[test_case("[10,20,30]:1~3", "[10, 20, 30]"; "slice all")]
#[test_case("[10,20,30,40,50]:[1,3,5]", "[10, 30, 50]"; "index by vector")]
#[test_case("[10,20,30,40,50]:[5,4,3,2,1]", "[50, 40, 30, 20, 10]"; "index reverse")]
#[test_case("1 in [1,2,3]", "1"; "in first")]
#[test_case("2 in [1,2,3]", "2"; "in middle")]
#[test_case("3 in [1,2,3]", "3"; "in last")]
#[test_case("[] = []", "[]"; "empty equal empty")]
#[test_case("[1,2,3] = [1,2,3]", "[1, 2, 3]"; "equal vectors")]
#[test_case("[1,2] < [2,3]", "[2, 3]"; "vector less than vector")]
#[test_case("[2,3] > [1,2]", "[1, 2]"; "vector greater than vector")]
#[test_case("[1/2, 1/3, 1/4] + [1/2, 2/3, 3/4]", "[1, 1, 1]"; "rational vector add")]
#[test_case("[1/2, 1/3] * [2, 3]", "[1, 1]"; "rational vector mul")]
#[test_case("[1, 2.0, 3/1] + [1, 1, 1]", "[2, 3, 4]"; "mixed type vector add")]
#[test_case("seq(1,5)", "[1, 2, 3, 4, 5]"; "range 1 to 5")]
#[test_case("seq(0,3)", "[0, 1, 2, 3]"; "range 0 to 3")]
#[test_case("seq(5,5)", "[5]"; "range singleton")]
#[test_case("seq(1,10,2)", "[1, 3, 5, 7, 9]"; "range odd numbers")]
#[test_case("seq(0,10,5)", "[0, 5, 10]"; "range by fives")]
#[test_case("seq(0,1,0.25)", "[0, 0.25, 0.5, 0.75, 1]"; "range float step")]
#[test_case("push([], 1)", "[1]"; "push to empty")]
#[test_case("push([1], 2)", "[1, 2]"; "push to singleton")]
#[test_case("push([1,2], 3, 4, 5)", "[1, 2, 3, 4, 5]"; "push multiple")]
fn vectors(input: &str, expexted: &str) {
    let (memory, funs) = init();
    let result = eval_string(input, memory, funs).expect("unexpected error");
    assert_eq!(result.to_string(), expexted)
}

#[test_case("1~5", "1~5"; "simple interval")]
#[test_case("0~0", "0~0"; "zero interval")]
#[test_case("-5~5", "-5~5"; "negative to positive")]
#[test_case("-10~-5", "-10~-5"; "negative interval")]
#[test_case("1.5~2.5", "1.5~2.5"; "float interval")]
#[test_case("(1~3) + (4~6)", "5~9"; "interval add")]
#[test_case("(5~10) - (1~3)", "2~9"; "interval sub")]
#[test_case("(2~4) * (3~5)", "6~20"; "interval mul")]
#[test_case("(10~20) / (2~5)", "2~10"; "interval div")]
#[test_case("(10~20) % (3~3)", "1~2"; "interval mod singular")]
#[test_case("(0~0) % (1~5)", "0~0"; "zero interval mod interval")]
#[test_case("(0~0) % (3~3)", "0~0"; "zero interval mod singular")]
#[test_case("(5~5) % (2~4)", "1~1"; "point dividend mod small interval")]
#[test_case("(5~12) % (4~4)", "0~1"; "interval mod point divisor")]
#[test_case("(10~25) % (7~7)", "3~4"; "interval mod point seven")]
#[test_case("(1~3) % (10~20)", "1~3"; "small interval mod large unchanged")]
#[test_case("(0~5) % (10~10)", "0~5"; "interval inside modulus")]
#[test_case("(2~4) % (100~200)", "2~4"; "tiny interval mod huge unchanged")]
#[test_case("(10~20) % (3~5)", "0~4.999999999999999"; "interval mod interval general")]
#[test_case("(15~25) % (4~6)", "0~5.999999999999999"; "interval mod interval overlap")]
#[test_case("(-10~-5) % (3~3)", "-2~-1"; "negative interval mod singular")]
#[test_case("(-20~-10) % (7~7)", "-6~-3"; "negative interval mod point")]
#[test_case("(-5~10) % (3~3)", "-2~1"; "spanning interval mod singular")]
#[test_case("(-3~5) % (10~10)", "-3~5"; "spanning inside modulus unchanged")]
#[test_case("(-10~15) % (7~7)", "-3~1"; "spanning interval mod point")]
#[test_case("(1~5) + 10", "11~15"; "interval add scalar")]
#[test_case("10 + (1~5)", "11~15"; "scalar add interval")]
#[test_case("(10~20) - 5", "5~15"; "interval sub scalar")]
#[test_case("100 - (10~20)", "80~90"; "scalar sub interval")]
#[test_case("(2~4) * 10", "20~40"; "interval mul scalar")]
#[test_case("10 * (2~4)", "20~40"; "scalar mul interval")]
#[test_case("(20~40) / 10", "2~4"; "interval div scalar")]
#[test_case("100 / (2~4)", "25~50"; "scalar div interval")]
#[test_case("(2~4)^2", "4~16"; "interval pow scalar")]
#[test_case("-(1~5)", "-5~-1"; "negate positive interval")]
#[test_case("-(-5~-1)", "1~5"; "negate negative interval")]
#[test_case("-(-5~5)", "-5~5"; "negate symmetric interval")]
#[test_case("(0~0) + (1~5)", "1~5"; "zero interval add")]
#[test_case("(1~5) + (0~0)", "1~5"; "add zero interval")]
#[test_case("(1~5) - (0~0)", "1~5"; "sub zero interval")]
#[test_case("(0~0) * (1~5)", "0~0"; "zero interval mul")]
#[test_case("(1~5) * (0~0)", "0~0"; "mul zero interval")]
#[test_case("(0~0) / (1~5)", "0~0"; "zero interval div")]
#[test_case("(1~5)^(0~0)", "1~1"; "interval pow zero")]
#[test_case("(1~5) * (1~1)", "1~5"; "interval mul one")]
#[test_case("(1~1) * (2~6)", "2~6"; "one interval mul")]
#[test_case("(2~6) / (1~1)", "2~6"; "interval div one")]
#[test_case("(2~5)^(1~1)", "2~5"; "interval pow one")]
#[test_case("(-5~-1) + (1~5)", "-4~4"; "negative interval add positive")]
#[test_case("(-5~-1) - (1~3)", "-8~-2"; "negative interval sub positive")]
#[test_case("(-5~-1) * (2~4)", "-20~-2"; "negative interval mul positive")]
#[test_case("(-3~-1) * (-5~-2)", "2~15"; "negative interval mul negative")]
#[test_case("(-2~3) * (-4~5)", "-12~15"; "spanning interval mul spanning")]
#[test_case("min(1~10)", "1"; "min of interval")]
#[test_case("max(1~10)", "10"; "max of interval")]
#[test_case("min(-5~5)", "-5"; "min of spanning interval")]
#[test_case("max(-5~5)", "5"; "max of spanning interval")]
#[test_case("(1~5) | (3~8)", "1~8"; "interval hull overlap")]
#[test_case("(1~3) | (5~8)", "1~8"; "interval hull disjoint")]
#[test_case("(-5~0) | (0~5)", "-5~5"; "interval hull touching")]
#[test_case("(1~5) & (3~8)", "3~5"; "interval intersection overlap")]
#[test_case("(-5~5) & (0~10)", "0~5"; "interval intersection spanning")]
#[test_case("(0~10) & (0~10)", "0~10"; "interval intersection same")]
#[test_case("5 in 1~10", "5"; "in interval middle")]
#[test_case("1 in 1~10", "1"; "in interval lower bound")]
#[test_case("10 in 1~10", "10"; "in interval upper bound")]
#[test_case("(1~5) < (10~20)", "10~20"; "interval less than interval")]
#[test_case("(10~20) > (1~5)", "1~5"; "interval greater than interval")]
#[test_case("1 < (5~10)", "5~10"; "scalar less than interval")]
#[test_case("(5~10) < 20", "20"; "interval less than scalar")]
#[test_case("(1~5) = (1~5)", "1~5"; "interval equal interval")]
#[test_case("(5~5) + (3~3)", "8~8"; "singular interval add")]
#[test_case("(5~5) * (3~3)", "15~15"; "singular interval mul")]
#[test_case("(10~10) / (2~2)", "5~5"; "singular interval div")]
#[test_case("(2~2)^(3~3)", "8~8"; "singular interval pow")]
#[test_case("(2~3)^2", "4~9"; "interval squared")]
#[test_case("(1~2)^3", "1~8"; "interval cubed")]
#[test_case("(4~9)^(1/2)", "2~3"; "interval sqrt")]
#[test_case("(2~4)^(1~2)", "2~16"; "interval pow interval")]
#[test_case("(5~10)^(0~0)", "1~1"; "interval pow zero interval")]
#[test_case("(-4~-2)^(1~1)", "-4~-2"; "negative interval pow one interval")]
#[test_case("(2~2)^(1~3)", "2~8"; "point base pow interval")]
#[test_case("(3~3)^(2~4)", "9~81"; "point base pow wider interval")]
#[test_case("(4~4)^(0~2)", "1~16"; "point base pow interval from zero")]
#[test_case("(1~4)^(2~2)", "1~16"; "interval pow point exponent")]
#[test_case("(2~5)^(3~3)", "8~125"; "interval pow point exponent cubed")]
#[test_case("(2~3)^(2~3)", "4~27"; "positive interval pow interval")]
#[test_case("(1~2)^(1~4)", "1~16"; "positive interval pow wider interval")]
#[test_case("(2~4)^(2~4)", "4~256"; "positive interval pow same range")]
#[test_case("(3~5)^(1~2)", "3~25"; "positive interval pow small interval")]
#[test_case("(-3~-2)^(2~2)", "4~9"; "negative interval pow even point")]
#[test_case("(-4~-2)^(2~4)", "-256~256"; "negative interval pow even interval")]
#[test_case("(-1~2)^(2~3)", "-1~8"; "spanning interval pow interval")]
#[test_case("(-3~2)^(1~2)", "-9~9"; "asymmetric spanning pow interval")]
#[test_case("(4~16)^((1/2)~(1/2))", "2~4"; "interval pow point half")]
#[test_case("(8~27)^((1/3)~(1/3))", "2~3"; "interval pow point third")]
#[test_case("(1~16)^((1/4)~(1/2))", "1~4"; "interval pow fractional interval")]
#[test_case("(4~9)^((1/2)~1)", "2~9"; "interval pow half to one")]
#[test_case("(1~8)^((1/3)~(2/3))", "1~4"; "interval pow fractional range")]
#[test_case("(-2~3)^(-1~1)", "-inf~inf"; "spanning pow negative exponent")]
#[test_case("(-5~5)^(-2~-1)", "-inf~inf"; "spanning pow fully negative exponent")]
#[test_case("(-1~1)^(-3~0)", "-inf~inf"; "unit spanning pow negative to zero")]
fn intervals(input: &str, expexted: &str) {
    let (memory, funs) = init();
    let result = eval_string(input, memory, funs).expect("unexpected error");
    assert_eq!(result.to_string(), expexted)
}
